# Generated by Django 4.1.2 on 2022-10-08 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razón social')),
                ('nit', models.CharField(max_length=12, verbose_name='NIT')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(max_length=7, verbose_name='Teléfono')),
                ('mobile', models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sitio web')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Portada')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/%Y/%m/%d', verbose_name='Logotipo')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['id'],
                'permissions': (('change_company', 'Can edit company'),),
                'default_permissions': (),
            },
        ),
    ]
