# Generated by Django 4.1.2 on 2022-10-08 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.company', verbose_name='Compañía'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='IVA'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Total IVA'),
        ),
    ]
